; pokemon ids
; indexes for:
; - PokemonNames (see data/pokemon/names.asm)
; - BaseData (see data/pokemon/base_stats.asm)
; - EvosAttacksPointers (see data/pokemon/evos_attacks_pointers.asm)
; - EggMovePointers (see data/pokemon/egg_move_pointers.asm)
; - PokemonCries (see data/pokemon/cries.asm)
; - MonMenuIcons (see data/pokemon/menu_icons.asm)
; - PokemonPicPointers (see data/pokemon/pic_pointers.asm)
; - PokemonPalettes (see data/pokemon/palettes.asm)
; - PokedexDataPointerTable (see data/pokemon/dex_entry_pointers.asm)
; - AlphabeticalPokedexOrder (see data/pokemon/dex_order_alpha.asm)
; - NewPokedexOrder (see data/pokemon/dex_order_new.asm)
; - Footprints (see gfx/footprints.asm)
	const_def 1
	const SNIVY      ; 01
	const SERVINE    ; 02
	const SERPERIOR  ; 03
	const TEPIG      ; 04
	const PIGNITE    ; 05
	const EMBOAR     ; 06
	const OSHAWOTT   ; 07
	const DEWOTT     ; 08
	const SAMUROTT   ; 09
	const PATRAT     ; 0a
	const WATCHOG    ; 0b
	const LILLIPUP   ; 0c
	const HERDIER    ; 0d
	const STOUTLAND  ; 0e
	const PURRLOIN   ; 0f
	const LIEPARD    ; 10
	const PANSAGE    ; 11
	const SIMISAGE   ; 12
	const PANSEAR    ; 13
	const SIMISEAR   ; 14
	const PANPOUR    ; 15
	const SIMIPOUR   ; 16
	const MUNNA      ; 17
	const MUSHARNA   ; 18
	const PIDOVE     ; 19
	const TRANQUILL  ; 1a
	const UNFEZANT   ; 1b
	const BLITZLE    ; 1c
	const ZEBSTRIKA  ; 1d
	const ROGGENROLA ; 1e
	const BOLDORE    ; 1f
	const GIGALITH   ; 20
	const WOOBAT     ; 21
	const SWOOBAT    ; 22
	const DRILBUR    ; 23
	const EXCADRILL  ; 24
	const AUDINO     ; 25
	const TIMBURR    ; 26
	const GURDURR    ; 27
	const CONKELDURR ; 28
	const TYMPOLE    ; 29
	const PALPITOAD  ; 2a
	const SEISMITOAD ; 2b
	const THROH      ; 2c
	const SAWK       ; 2d
	const SEWADDLE   ; 2e
	const SWADLOON   ; 2f
	const LEAVANNY   ; 30
	const VENIPEDE   ; 31
	const WHIRLIPEDE ; 32
	const SCOLIPEDE  ; 33
	const COTTONEE   ; 34
	const WHIMSICOTT ; 35
	const PETILIL    ; 36
	const LILLIGANT  ; 37
	const BASCULIN   ; 38
	const SANDILE    ; 39
	const KROKOROK   ; 3a
	const KROOKODILE ; 3b
	const DARUMAKA   ; 3c
	const DARMANITAN ; 3d
	const MARACTUS   ; 3e
	const DWEBBLE    ; 3f
	const CRUSTLE    ; 40
	const SCRAGGY    ; 41
	const SCRAFTY    ; 42
	const SIGILYPH   ; 43
	const YAMASK     ; 44
	const COFAGRIGUS ; 45
	const TIRTOUGA   ; 46
	const CARRACOSTA ; 47
	const ARCHEN     ; 48
	const ARCHEOPS   ; 49
	const TRUBBISH   ; 4a
	const GARBODOR   ; 4b
	const ZORUA      ; 4c
	const ZOROARK    ; 4d
	const MINCCINO   ; 4e
	const CINCCINO   ; 4f
	const GOTHITA    ; 50
	const GOTHORITA  ; 51
	const GOTHITELLE ; 52
	const SOLOSIS    ; 53
	const DUOSION    ; 54
	const REUNICLUS  ; 55
	const DUCKLETT   ; 56
	const SWANNA     ; 57
	const VANILLITE  ; 58
	const VANILLISH  ; 59
	const VANILLUXE  ; 5a
	const DEERLING   ; 5b
	const SAWSBUCK   ; 5c
	const EMOLGA     ; 5d
	const KARRABLAST ; 5e
	const ESCAVALIER ; 5f
	const FOONGUS    ; 60
	const AMOONGUSS  ; 61
	const FRILLISH   ; 62
	const JELLICENT  ; 63
	const ALOMOMOLA  ; 64
	const JOLTIK     ; 65
	const GALVANTULA ; 66
	const FERROSEED  ; 67
	const FERROTHORN ; 68
	const KLINK      ; 69
	const KLANG      ; 6a
	const KLINKLANG  ; 6b
	const TYNAMO     ; 6c
	const EELEKTRIK  ; 6d
	const EELEKTROSS ; 6e
	const ELGYEM     ; 6f
	const BEHEEYEM   ; 70
	const LITWICK    ; 71
	const LAMPENT    ; 72
	const CHANDELURE ; 73
	const AXEW       ; 74
	const FRAXURE    ; 75
	const HAXORUS    ; 76
	const CUBCHOO    ; 77
	const BEARTIC    ; 78
	const CRYOGONAL  ; 79
	const SHELMET    ; 7a
	const ACCELGOR   ; 7b
	const STUNFISK   ; 7c
	const MIENFOO    ; 7d
	const MIENSHAO   ; 7e
	const DRUDDIGON  ; 7f
	const GOLETT     ; 80
	const MAGIKARP   ; 81
	const GYARADOS   ; 82
	const LAPRAS     ; 83
	const DITTO      ; 84
	const EEVEE      ; 85
	const VAPOREON   ; 86
	const JOLTEON    ; 87
	const FLAREON    ; 88
	const PORYGON    ; 89
	const OMANYTE    ; 8a
	const OMASTAR    ; 8b
	const KABUTO     ; 8c
	const KABUTOPS   ; 8d
	const AERODACTYL ; 8e
	const SNORLAX    ; 8f
	const ARTICUNO   ; 90
	const ZAPDOS     ; 91
	const MOLTRES    ; 92
	const DRATINI    ; 93
	const DRAGONAIR  ; 94
	const DRAGONITE  ; 95
	const MEWTWO     ; 96
	const MEW        ; 97
DEF JOHTO_POKEMON EQU const_value
	const CHIKORITA  ; 98
	const BAYLEEF    ; 99
	const MEGANIUM   ; 9a
	const CYNDAQUIL  ; 9b
	const QUILAVA    ; 9c
	const TYPHLOSION ; 9d
	const TOTODILE   ; 9e
	const CROCONAW   ; 9f
	const FERALIGATR ; a0
	const RATTATA    ; a1
	const RATICATE   ; a2
	const CLEFAIRY   ; a3
	const CLEFABLE   ; a4
	const VULPIX     ; a5
	const NINETALES  ; a6
	const LEDYBA     ; a7
	const LEDIAN     ; a8
	const SPINARAK   ; a9
	const ARIADOS    ; aa
	const PSYDUCK    ; ab
	const GOLDUCK    ; ac
	const CLEFFA     ; ad
	const GROWLITHE  ; ae
	const ARCANINE   ; af
	const MAGNEMITE  ; b0
	const MAGNETON   ; b1
	const FARFETCH_D ; b2
	const MAREEP     ; b3
	const FLAAFFY    ; b4
	const AMPHAROS   ; b5
	const GRIMER     ; b6
	const MUK        ; b7
	const KOFFING    ; b8
	const WEEZING    ; b9
	const CHANSEY    ; ba
	const TANGELA    ; bb
	const JYNX       ; bc
	const ELECTABUZZ ; bd
	const MAGMAR     ; be
	const SUNKERN    ; bf
	const SUNFLORA   ; c0
	const YANMA      ; c1
	const WOOPER     ; c2
	const QUAGSIRE   ; c3
	const ESPEON     ; c4
	const UMBREON    ; c5
	const MURKROW    ; c6
	const SLOWKING   ; c7
	const MISDREAVUS ; c8
	const UNOWN      ; c9
	const WOBBUFFET  ; ca
	const GIRAFARIG  ; cb
	const PINECO     ; cc
	const FORRETRESS ; cd
	const DUNSPARCE  ; ce
	const GLIGAR     ; cf
	const STEELIX    ; d0
	const SNUBBULL   ; d1
	const GRANBULL   ; d2
	const QWILFISH   ; d3
	const SCIZOR     ; d4
	const SHUCKLE    ; d5
	const HERACROSS  ; d6
	const SNEASEL    ; d7
	const TEDDIURSA  ; d8
	const URSARING   ; d9
	const SLUGMA     ; da
	const MAGCARGO   ; db
	const SWINUB     ; dc
	const PILOSWINE  ; dd
	const CORSOLA    ; de
	const REMORAID   ; df
	const OCTILLERY  ; e0
	const DELIBIRD   ; e1
	const MANTINE    ; e2
	const SKARMORY   ; e3
	const HOUNDOUR   ; e4
	const HOUNDOOM   ; e5
	const KINGDRA    ; e6
	const PHANPY     ; e7
	const DONPHAN    ; e8
	const PORYGON2   ; e9
	const STANTLER   ; ea
	const SMEARGLE   ; eb
	const TYROGUE    ; ec
	const HITMONTOP  ; ed
	const SMOOCHUM   ; ee
	const ELEKID     ; ef
	const MAGBY      ; f0
	const MILTANK    ; f1
	const BLISSEY    ; f2
	const RAIKOU     ; f3
	const ENTEI      ; f4
	const SUICUNE    ; f5
	const LARVITAR   ; f6
	const PUPITAR    ; f7
	const TYRANITAR  ; f8
	const LUGIA      ; f9
	const HO_OH      ; fa
	const CELEBI     ; fb
	const POOCHYENA  ; fc
	const MIGHTYENA  ; fd
DEF NUM_POKEMON EQU const_value - 1
	const EGG        ; fe

; Unown forms
; indexes for:
; - UnownWords (see data/pokemon/unown_words.asm)
; - UnownPicPointers (see data/pokemon/unown_pic_pointers.asm)
; - UnownAnimationPointers (see gfx/pokemon/unown_anim_pointers.asm)
; - UnownAnimationIdlePointers (see gfx/pokemon/unown_idle_pointers.asm)
; - UnownBitmasksPointers (see gfx/pokemon/unown_bitmask_pointers.asm)
; - UnownFramesPointers (see gfx/pokemon/unown_frame_pointers.asm)
	const_def 1
	const UNOWN_A ;  1
	const UNOWN_B ;  2
	const UNOWN_C ;  3
	const UNOWN_D ;  4
	const UNOWN_E ;  5
	const UNOWN_F ;  6
	const UNOWN_G ;  7
	const UNOWN_H ;  8
	const UNOWN_I ;  9
	const UNOWN_J ; 10
	const UNOWN_K ; 11
	const UNOWN_L ; 12
	const UNOWN_M ; 13
	const UNOWN_N ; 14
	const UNOWN_O ; 15
	const UNOWN_P ; 16
	const UNOWN_Q ; 17
	const UNOWN_R ; 18
	const UNOWN_S ; 19
	const UNOWN_T ; 20
	const UNOWN_U ; 21
	const UNOWN_V ; 22
	const UNOWN_W ; 23
	const UNOWN_X ; 24
	const UNOWN_Y ; 25
	const UNOWN_Z ; 26
DEF NUM_UNOWN EQU const_value - 1 ; 26
