; PokemonPicPointers and UnownPicPointers are assumed to start at the same
; address, but in different banks. This is enforced in layout.link.


SECTION "Pic Pointers", ROMX

INCLUDE "data/pokemon/pic_pointers.asm"


SECTION "Female Pic Pointers", ROMX

INCLUDE "data/pokemon/female_pic_pointers.asm"


SECTION "Unown Pic Pointers", ROMX

INCLUDE "data/pokemon/unown_pic_pointers.asm"


SECTION "Trainer Pic Pointers", ROMX

INCLUDE "data/trainers/pic_pointers.asm"


SECTION "Pics 1", ROMX

SwoobatFrontpic:     INCBIN "gfx/pokemon/swoobat/front.2bpp.lz"
HoOhFrontpic:        INCBIN "gfx/pokemon/ho_oh/front.2bpp.lz"
GyaradosFrontpic:    INCBIN "gfx/pokemon/gyarados/front.2bpp.lz"
MeganiumFrontpic:    INCBIN "gfx/pokemon/meganium/front.2bpp.lz"
YamaskFrontpic:      INCBIN "gfx/pokemon/yamask/front.2bpp.lz"
FeraligatrFrontpic:  INCBIN "gfx/pokemon/feraligatr/front.2bpp.lz"
SteelixFrontpic:     INCBIN "gfx/pokemon/steelix/front.2bpp.lz"
NinetalesFrontpic:   INCBIN "gfx/pokemon/ninetales/front.2bpp.lz"
BeheeyemFrontpic:    INCBIN "gfx/pokemon/beheeyem/front.2bpp.lz"
RaikouFrontpic:      INCBIN "gfx/pokemon/raikou/front.2bpp.lz"
GolettFrontpic:      INCBIN "gfx/pokemon/golett/front.2bpp.lz"
BoldoreFrontpic:     INCBIN "gfx/pokemon/boldore/front.2bpp.lz"
MinccinoFrontpic:    INCBIN "gfx/pokemon/minccino/front.2bpp.lz"
EnteiFrontpic:       INCBIN "gfx/pokemon/entei/front.2bpp.lz"
ChandelureFrontpic:  INCBIN "gfx/pokemon/chandelure/front.2bpp.lz"
SamurottFrontpic:    INCBIN "gfx/pokemon/samurott/front.2bpp.lz"
MusharnaFrontpic:    INCBIN "gfx/pokemon/musharna/front.2bpp.lz"
EmboarFrontpic:      INCBIN "gfx/pokemon/emboar/front.2bpp.lz"
SkarmoryFrontpic:    INCBIN "gfx/pokemon/skarmory/front.2bpp.lz"
WeezingFrontpic:     INCBIN "gfx/pokemon/weezing/front.2bpp.lz"
SerperiorFrontpic:   INCBIN "gfx/pokemon/serperior/front.2bpp.lz"
PurrloinFrontpic:    INCBIN "gfx/pokemon/purrloin/front.2bpp.lz"
LugiaFrontpic:       INCBIN "gfx/pokemon/lugia/front.2bpp.lz"
WoobatFrontpic:      INCBIN "gfx/pokemon/woobat/front.2bpp.lz"


SECTION "Pics 2", ROMX

MienfooFrontpic:     INCBIN "gfx/pokemon/mienfoo/front.2bpp.lz"
SmeargleFrontpic:    INCBIN "gfx/pokemon/smeargle/front.2bpp.lz"
FerroseedBackpic:    INCBIN "gfx/pokemon/ferroseed/back.2bpp.lz"
MagcargoFrontpic:    INCBIN "gfx/pokemon/magcargo/front.2bpp.lz"
LaprasFrontpic:      INCBIN "gfx/pokemon/lapras/front.2bpp.lz"
TynamoFrontpic:      INCBIN "gfx/pokemon/tynamo/front.2bpp.lz"
ChuckPic:            INCBIN "gfx/trainers/chuck.2bpp.lz"
SwadloonFrontpic:    INCBIN "gfx/pokemon/swadloon/front.2bpp.lz"
LillipupBackpic:     INCBIN "gfx/pokemon/lillipup/back.2bpp.lz"
KimonoGirlPic:       INCBIN "gfx/trainers/kimono_girl.2bpp.lz"
SimipourFrontpic:    INCBIN "gfx/pokemon/simipour/front.2bpp.lz"
ScraggyBackpic:      INCBIN "gfx/pokemon/scraggy/back.2bpp.lz"
GirafarigFrontpic:   INCBIN "gfx/pokemon/girafarig/front.2bpp.lz"
PalpitoadFrontpic:   INCBIN "gfx/pokemon/palpitoad/front.2bpp.lz"
KoffingFrontpic:     INCBIN "gfx/pokemon/koffing/front.2bpp.lz"
DeerlingBackpic:     INCBIN "gfx/pokemon/deerling/back.2bpp.lz"
HitmontopBackpic:    INCBIN "gfx/pokemon/hitmontop/back.2bpp.lz"
FoongusFrontpic:     INCBIN "gfx/pokemon/foongus/front.2bpp.lz"
CryogonalFrontpic:   INCBIN "gfx/pokemon/cryogonal/front.2bpp.lz"
KabutopsFrontpic:    INCBIN "gfx/pokemon/kabutops/front.2bpp.lz"
ReuniclusBackpic:    INCBIN "gfx/pokemon/reuniclus/back.2bpp.lz"
KlangFrontpic:       INCBIN "gfx/pokemon/klang/front.2bpp.lz"
VenipedeFrontpic:    INCBIN "gfx/pokemon/venipede/front.2bpp.lz"
BayleefFrontpic:     INCBIN "gfx/pokemon/bayleef/front.2bpp.lz"
JugglerPic:          INCBIN "gfx/trainers/juggler.2bpp.lz"
GuitaristPic:        INCBIN "gfx/trainers/guitarist.2bpp.lz"
PokefanfPic:         INCBIN "gfx/trainers/pokefan_f.2bpp.lz"
VenipedeBackpic:     INCBIN "gfx/pokemon/venipede/back.2bpp.lz"
ExcadrillFrontpic:   INCBIN "gfx/pokemon/excadrill/front.2bpp.lz"
ClairPic:            INCBIN "gfx/trainers/clair.2bpp.lz"
PokemaniacPic:       INCBIN "gfx/trainers/pokemaniac.2bpp.lz"
OmastarFrontpic:     INCBIN "gfx/pokemon/omastar/front.2bpp.lz"
SkierPic:            INCBIN "gfx/trainers/skier.2bpp.lz"
LugiaBackpic:        INCBIN "gfx/pokemon/lugia/back.2bpp.lz"


SECTION "Pics 3", ROMX

ChandelureBackpic:   INCBIN "gfx/pokemon/chandelure/back.2bpp.lz"
GligarFrontpic:      INCBIN "gfx/pokemon/gligar/front.2bpp.lz"
FarfetchDFrontpic:   INCBIN "gfx/pokemon/farfetch_d/front.2bpp.lz"
MagnetonFrontpic:    INCBIN "gfx/pokemon/magneton/front.2bpp.lz"
AmpharosFrontpic:    INCBIN "gfx/pokemon/ampharos/front.2bpp.lz"
AccelgorFrontpic:    INCBIN "gfx/pokemon/accelgor/front.2bpp.lz"
HoundoomFrontpic:    INCBIN "gfx/pokemon/houndoom/front.2bpp.lz"
JolteonFrontpic:     INCBIN "gfx/pokemon/jolteon/front.2bpp.lz"
RoggenrolaFrontpic:  INCBIN "gfx/pokemon/roggenrola/front.2bpp.lz"
GyaradosBackpic:     INCBIN "gfx/pokemon/gyarados/back.2bpp.lz"
RaticateFrontpic:    INCBIN "gfx/pokemon/raticate/front.2bpp.lz"
YanmaBackpic:        INCBIN "gfx/pokemon/yanma/back.2bpp.lz"
HeracrossFrontpic:   INCBIN "gfx/pokemon/heracross/front.2bpp.lz"
SneaselFrontpic:     INCBIN "gfx/pokemon/sneasel/front.2bpp.lz"
ZoruaFrontpic:       INCBIN "gfx/pokemon/zorua/front.2bpp.lz"
ElekidFrontpic:      INCBIN "gfx/pokemon/elekid/front.2bpp.lz"
OmastarBackpic:      INCBIN "gfx/pokemon/omastar/back.2bpp.lz"
ClefableBackpic:     INCBIN "gfx/pokemon/clefable/back.2bpp.lz"
LassPic:             INCBIN "gfx/trainers/lass.2bpp.lz"
MiltankFrontpic:     INCBIN "gfx/pokemon/miltank/front.2bpp.lz"
FeraligatrBackpic:   INCBIN "gfx/pokemon/feraligatr/back.2bpp.lz"
MagnetonBackpic:     INCBIN "gfx/pokemon/magneton/back.2bpp.lz"
SawsbuckFrontpic:    INCBIN "gfx/pokemon/sawsbuck/front.2bpp.lz"
FlareonFrontpic:     INCBIN "gfx/pokemon/flareon/front.2bpp.lz"
GranbullFrontpic:    INCBIN "gfx/pokemon/granbull/front.2bpp.lz"
SuicuneBackpic:      INCBIN "gfx/pokemon/suicune/back.2bpp.lz"
SlowkingBackpic:     INCBIN "gfx/pokemon/slowking/back.2bpp.lz"
PigniteFrontpic:     INCBIN "gfx/pokemon/pignite/front.2bpp.lz"
DewottFrontpic:      INCBIN "gfx/pokemon/dewott/front.2bpp.lz"
DucklettFrontpic:    INCBIN "gfx/pokemon/ducklett/front.2bpp.lz"
AriadosFrontpic:     INCBIN "gfx/pokemon/ariados/front.2bpp.lz"
ElekidBackpic:       INCBIN "gfx/pokemon/elekid/back.2bpp.lz"
QuilavaFrontpic:     INCBIN "gfx/pokemon/quilava/front.2bpp.lz"
CelebiBackpic:       INCBIN "gfx/pokemon/celebi/back.2bpp.lz"
FrillishBackpic:     INCBIN "gfx/pokemon/frillish/back.2bpp.lz"
BugCatcherPic:       INCBIN "gfx/trainers/bug_catcher.2bpp.lz"


SECTION "Pics 4", ROMX

ZoroarkFrontpic:     INCBIN "gfx/pokemon/zoroark/front.2bpp.lz"
SunfloraBackpic:     INCBIN "gfx/pokemon/sunflora/back.2bpp.lz"
DragonairFrontpic:   INCBIN "gfx/pokemon/dragonair/front.2bpp.lz"
TyranitarBackpic:    INCBIN "gfx/pokemon/tyranitar/back.2bpp.lz"
BeheeyemBackpic:     INCBIN "gfx/pokemon/beheeyem/back.2bpp.lz"
FraxureBackpic:      INCBIN "gfx/pokemon/fraxure/back.2bpp.lz"
TwinsPic:            INCBIN "gfx/trainers/twins.2bpp.lz"
DarmanitanFrontpic:  INCBIN "gfx/pokemon/darmanitan/front.2bpp.lz"
CroconawFrontpic:    INCBIN "gfx/pokemon/croconaw/front.2bpp.lz"
BlitzleBackpic:      INCBIN "gfx/pokemon/blitzle/back.2bpp.lz"
GigalithBackpic:     INCBIN "gfx/pokemon/gigalith/back.2bpp.lz"
TangelaFrontpic:     INCBIN "gfx/pokemon/tangela/front.2bpp.lz"
LedybaBackpic:       INCBIN "gfx/pokemon/ledyba/back.2bpp.lz"
FarfetchDBackpic:    INCBIN "gfx/pokemon/farfetch_d/back.2bpp.lz"
CyndaquilBackpic:    INCBIN "gfx/pokemon/cyndaquil/back.2bpp.lz"
ChanseyFrontpic:     INCBIN "gfx/pokemon/chansey/front.2bpp.lz"
MagmarBackpic:       INCBIN "gfx/pokemon/magmar/back.2bpp.lz"
VulpixFrontpic:      INCBIN "gfx/pokemon/vulpix/front.2bpp.lz"
NinetalesBackpic:    INCBIN "gfx/pokemon/ninetales/back.2bpp.lz"
BayleefBackpic:      INCBIN "gfx/pokemon/bayleef/back.2bpp.lz"
CroconawBackpic:     INCBIN "gfx/pokemon/croconaw/back.2bpp.lz"
MinccinoBackpic:     INCBIN "gfx/pokemon/minccino/back.2bpp.lz"
DuosionBackpic:      INCBIN "gfx/pokemon/duosion/back.2bpp.lz"
DelibirdFrontpic:    INCBIN "gfx/pokemon/delibird/front.2bpp.lz"
GothoritaFrontpic:   INCBIN "gfx/pokemon/gothorita/front.2bpp.lz"
EspeonFrontpic:      INCBIN "gfx/pokemon/espeon/front.2bpp.lz"
PetililFrontpic:     INCBIN "gfx/pokemon/petilil/front.2bpp.lz"
BasculinBackpic:     INCBIN "gfx/pokemon/basculin/back.2bpp.lz"
ThrohFrontpic:       INCBIN "gfx/pokemon/throh/front.2bpp.lz"
AmoongussBackpic:    INCBIN "gfx/pokemon/amoonguss/back.2bpp.lz"
TyphlosionBackpic:   INCBIN "gfx/pokemon/typhlosion/back.2bpp.lz"
YanmaFrontpic:       INCBIN "gfx/pokemon/yanma/front.2bpp.lz"
QuilavaBackpic:      INCBIN "gfx/pokemon/quilava/back.2bpp.lz"
SimisearFrontpic:    INCBIN "gfx/pokemon/simisear/front.2bpp.lz"
UnfezantBackpic:     INCBIN "gfx/pokemon/unfezant/back.2bpp.lz"
BeautyPic:           INCBIN "gfx/trainers/beauty.2bpp.lz"
SailorPic:           INCBIN "gfx/trainers/sailor.2bpp.lz"
TympoleBackpic:      INCBIN "gfx/pokemon/tympole/back.2bpp.lz"
UnownUFrontpic:      INCBIN "gfx/pokemon/unown_u/front.2bpp.lz"


SECTION "Pics 5", ROMX

VanilluxeBackpic:    INCBIN "gfx/pokemon/vanilluxe/back.2bpp.lz"
SunfloraFrontpic:    INCBIN "gfx/pokemon/sunflora/front.2bpp.lz"
PurrloinBackpic:     INCBIN "gfx/pokemon/purrloin/back.2bpp.lz"
GruntmPic:           INCBIN "gfx/trainers/grunt_m.2bpp.lz"
ThrohBackpic:        INCBIN "gfx/pokemon/throh/back.2bpp.lz"
FerrothornBackpic:   INCBIN "gfx/pokemon/ferrothorn/back.2bpp.lz"
KabutopsBackpic:     INCBIN "gfx/pokemon/kabutops/back.2bpp.lz"
VanilliteFrontpic:   INCBIN "gfx/pokemon/vanillite/front.2bpp.lz"
HaxorusBackpic:      INCBIN "gfx/pokemon/haxorus/back.2bpp.lz"
ArcanineBackpic:     INCBIN "gfx/pokemon/arcanine/back.2bpp.lz"
FlareonBackpic:      INCBIN "gfx/pokemon/flareon/back.2bpp.lz"
SawkFrontpic:        INCBIN "gfx/pokemon/sawk/front.2bpp.lz"
OmanyteBackpic:      INCBIN "gfx/pokemon/omanyte/back.2bpp.lz"
EelektrossFrontpic:  INCBIN "gfx/pokemon/eelektross/front.2bpp.lz"
ScientistPic:        INCBIN "gfx/trainers/scientist.2bpp.lz"
LiepardBackpic:      INCBIN "gfx/pokemon/liepard/back.2bpp.lz"
MisdreavusFrontpic:  INCBIN "gfx/pokemon/misdreavus/front.2bpp.lz"
PansageFrontpic:     INCBIN "gfx/pokemon/pansage/front.2bpp.lz"
QwilfishBackpic:     INCBIN "gfx/pokemon/qwilfish/back.2bpp.lz"
ClefableFrontpic:    INCBIN "gfx/pokemon/clefable/front.2bpp.lz"
GligarBackpic:       INCBIN "gfx/pokemon/gligar/back.2bpp.lz"
EmolgaFrontpic:      INCBIN "gfx/pokemon/emolga/front.2bpp.lz"
PigniteBackpic:      INCBIN "gfx/pokemon/pignite/back.2bpp.lz"
MagcargoBackpic:     INCBIN "gfx/pokemon/magcargo/back.2bpp.lz"
BoldoreBackpic:      INCBIN "gfx/pokemon/boldore/back.2bpp.lz"
GrimerBackpic:       INCBIN "gfx/pokemon/grimer/back.2bpp.lz"
ElectabuzzBackpic:   INCBIN "gfx/pokemon/electabuzz/back.2bpp.lz"
PiloswineFrontpic:   INCBIN "gfx/pokemon/piloswine/front.2bpp.lz"
LedianBackpic:       INCBIN "gfx/pokemon/ledian/back.2bpp.lz"
HeracrossBackpic:    INCBIN "gfx/pokemon/heracross/back.2bpp.lz"
SteelixBackpic:      INCBIN "gfx/pokemon/steelix/back.2bpp.lz"
WhimsicottBackpic:   INCBIN "gfx/pokemon/whimsicott/back.2bpp.lz"
KlinkFrontpic:       INCBIN "gfx/pokemon/klink/front.2bpp.lz"
LtSurgePic:          INCBIN "gfx/trainers/lt_surge.2bpp.lz"
TeacherPic:          INCBIN "gfx/trainers/teacher.2bpp.lz"
EeveeBackpic:        INCBIN "gfx/pokemon/eevee/back.2bpp.lz"
KarrablastFrontpic:  INCBIN "gfx/pokemon/karrablast/front.2bpp.lz"
ZoroarkBackpic:      INCBIN "gfx/pokemon/zoroark/back.2bpp.lz"
PupitarBackpic:      INCBIN "gfx/pokemon/pupitar/back.2bpp.lz"
KoffingBackpic:      INCBIN "gfx/pokemon/koffing/back.2bpp.lz"


SECTION "Pics 6", ROMX

GirafarigBackpic:    INCBIN "gfx/pokemon/girafarig/back.2bpp.lz"
BirdKeeperPic:       INCBIN "gfx/trainers/bird_keeper.2bpp.lz"
EscavalierBackpic:   INCBIN "gfx/pokemon/escavalier/back.2bpp.lz"
FalknerPic:          INCBIN "gfx/trainers/falkner.2bpp.lz"
OctilleryFrontpic:   INCBIN "gfx/pokemon/octillery/front.2bpp.lz"
GothoritaBackpic:    INCBIN "gfx/pokemon/gothorita/back.2bpp.lz"
MiltankBackpic:      INCBIN "gfx/pokemon/miltank/back.2bpp.lz"
KarenPic:            INCBIN "gfx/trainers/karen.2bpp.lz"
GrowlitheBackpic:    INCBIN "gfx/pokemon/growlithe/back.2bpp.lz"
SigilyphBackpic:     INCBIN "gfx/pokemon/sigilyph/back.2bpp.lz"
KogaPic:             INCBIN "gfx/trainers/koga.2bpp.lz"
TranquillBackpic:    INCBIN "gfx/pokemon/tranquill/back.2bpp.lz"
ArcheopsBackpic:     INCBIN "gfx/pokemon/archeops/back.2bpp.lz"
RoggenrolaBackpic:   INCBIN "gfx/pokemon/roggenrola/back.2bpp.lz"
MaractusBackpic:     INCBIN "gfx/pokemon/maractus/back.2bpp.lz"
FraxureFrontpic:     INCBIN "gfx/pokemon/fraxure/front.2bpp.lz"
ConkeldurrFrontpic:  INCBIN "gfx/pokemon/conkeldurr/front.2bpp.lz"
SwimmermPic:         INCBIN "gfx/trainers/swimmer_m.2bpp.lz"
MienfooBackpic:      INCBIN "gfx/pokemon/mienfoo/back.2bpp.lz"
FlaaffyBackpic:      INCBIN "gfx/pokemon/flaaffy/back.2bpp.lz"
DruddigonBackpic:    INCBIN "gfx/pokemon/druddigon/back.2bpp.lz"
WoobatBackpic:       INCBIN "gfx/pokemon/woobat/back.2bpp.lz"
CooltrainerfPic:     INCBIN "gfx/trainers/cooltrainer_f.2bpp.lz"
UmbreonBackpic:      INCBIN "gfx/pokemon/umbreon/back.2bpp.lz"
EelektrossBackpic:   INCBIN "gfx/pokemon/eelektross/back.2bpp.lz"
BugsyPic:            INCBIN "gfx/trainers/bugsy.2bpp.lz"
KlinkBackpic:        INCBIN "gfx/pokemon/klink/back.2bpp.lz"
CorsolaFrontpic:     INCBIN "gfx/pokemon/corsola/front.2bpp.lz"
TrubbishBackpic:     INCBIN "gfx/pokemon/trubbish/back.2bpp.lz"
LedianFrontpic:      INCBIN "gfx/pokemon/ledian/front.2bpp.lz"
HoundoomBackpic:     INCBIN "gfx/pokemon/houndoom/back.2bpp.lz"
AccelgorBackpic:     INCBIN "gfx/pokemon/accelgor/back.2bpp.lz"
SawkBackpic:         INCBIN "gfx/pokemon/sawk/back.2bpp.lz"
ScolipedeFrontpic:   INCBIN "gfx/pokemon/scolipede/front.2bpp.lz"
AudinoFrontpic:      INCBIN "gfx/pokemon/audino/front.2bpp.lz"
KlinklangBackpic:    INCBIN "gfx/pokemon/klinklang/back.2bpp.lz"
SamurottBackpic:     INCBIN "gfx/pokemon/samurott/back.2bpp.lz"
CooltrainermPic:     INCBIN "gfx/trainers/cooltrainer_m.2bpp.lz"
MisdreavusBackpic:   INCBIN "gfx/pokemon/misdreavus/back.2bpp.lz"
ScizorBackpic:       INCBIN "gfx/pokemon/scizor/back.2bpp.lz"
SmeargleBackpic:     INCBIN "gfx/pokemon/smeargle/back.2bpp.lz"


SECTION "Pics 7", ROMX

CrustleBackpic:      INCBIN "gfx/pokemon/crustle/back.2bpp.lz"
SandileBackpic:      INCBIN "gfx/pokemon/sandile/back.2bpp.lz"
PupitarFrontpic:     INCBIN "gfx/pokemon/pupitar/front.2bpp.lz"
DewottBackpic:       INCBIN "gfx/pokemon/dewott/back.2bpp.lz"
SimisearBackpic:     INCBIN "gfx/pokemon/simisear/back.2bpp.lz"
GalvantulaBackpic:   INCBIN "gfx/pokemon/galvantula/back.2bpp.lz"
VulpixBackpic:       INCBIN "gfx/pokemon/vulpix/back.2bpp.lz"
RaticateBackpic:     INCBIN "gfx/pokemon/raticate/back.2bpp.lz"
MunnaBackpic:        INCBIN "gfx/pokemon/munna/back.2bpp.lz"
CottoneeFrontpic:    INCBIN "gfx/pokemon/cottonee/front.2bpp.lz"
BurglarPic:          INCBIN "gfx/trainers/burglar.2bpp.lz"
CubchooBackpic:      INCBIN "gfx/pokemon/cubchoo/back.2bpp.lz"
PsyduckBackpic:      INCBIN "gfx/pokemon/psyduck/back.2bpp.lz"
PidoveBackpic:       INCBIN "gfx/pokemon/pidove/back.2bpp.lz"
TirtougaFrontpic:    INCBIN "gfx/pokemon/tirtouga/front.2bpp.lz"
RemoraidBackpic:     INCBIN "gfx/pokemon/remoraid/back.2bpp.lz"
MareepBackpic:       INCBIN "gfx/pokemon/mareep/back.2bpp.lz"
KingdraBackpic:      INCBIN "gfx/pokemon/kingdra/back.2bpp.lz"
CamperPic:           INCBIN "gfx/trainers/camper.2bpp.lz"
ClefairyBackpic:     INCBIN "gfx/pokemon/clefairy/back.2bpp.lz"
LeavannyBackpic:     INCBIN "gfx/pokemon/leavanny/back.2bpp.lz"
SnubbullFrontpic:    INCBIN "gfx/pokemon/snubbull/front.2bpp.lz"
PokemonProfPic:      INCBIN "gfx/trainers/oak.2bpp.lz"
MewtwoBackpic:       INCBIN "gfx/pokemon/mewtwo/back.2bpp.lz"
Rival1Pic:           INCBIN "gfx/trainers/rival1.2bpp.lz"
VanilliteBackpic:    INCBIN "gfx/pokemon/vanillite/back.2bpp.lz"
SwimmerfPic:         INCBIN "gfx/trainers/swimmer_f.2bpp.lz"
CalPic:              INCBIN "gfx/trainers/cal.2bpp.lz"
OfficerPic:          INCBIN "gfx/trainers/officer.2bpp.lz"
FrillishFrontpic:    INCBIN "gfx/pokemon/frillish/front.2bpp.lz"
ServineFrontpic:     INCBIN "gfx/pokemon/servine/front.2bpp.lz"
MukBackpic:          INCBIN "gfx/pokemon/muk/back.2bpp.lz"
DelibirdBackpic:     INCBIN "gfx/pokemon/delibird/back.2bpp.lz"
TimburrFrontpic:     INCBIN "gfx/pokemon/timburr/front.2bpp.lz"
SabrinaPic:          INCBIN "gfx/trainers/sabrina.2bpp.lz"
MagikarpBackpic:     INCBIN "gfx/pokemon/magikarp/back.2bpp.lz"
AriadosBackpic:      INCBIN "gfx/pokemon/ariados/back.2bpp.lz"
TyrogueBackpic:      INCBIN "gfx/pokemon/tyrogue/back.2bpp.lz"
WobbuffetFrontpic:   INCBIN "gfx/pokemon/wobbuffet/front.2bpp.lz"
KlinklangFrontpic:   INCBIN "gfx/pokemon/klinklang/front.2bpp.lz"
MurkrowBackpic:      INCBIN "gfx/pokemon/murkrow/back.2bpp.lz"
ServineBackpic:      INCBIN "gfx/pokemon/servine/back.2bpp.lz"
SolosisFrontpic:     INCBIN "gfx/pokemon/solosis/front.2bpp.lz"
GothitaBackpic:      INCBIN "gfx/pokemon/gothita/back.2bpp.lz"
ZebstrikaFrontpic:   INCBIN "gfx/pokemon/zebstrika/front.2bpp.lz"


SECTION "Pics 8", ROMX

PsychicTPic:         INCBIN "gfx/trainers/psychic_t.2bpp.lz"
GolduckBackpic:      INCBIN "gfx/pokemon/golduck/back.2bpp.lz"
WeezingBackpic:      INCBIN "gfx/pokemon/weezing/back.2bpp.lz"
SneaselBackpic:      INCBIN "gfx/pokemon/sneasel/back.2bpp.lz"
GrimerFrontpic:      INCBIN "gfx/pokemon/grimer/front.2bpp.lz"
DunsparceFrontpic:   INCBIN "gfx/pokemon/dunsparce/front.2bpp.lz"
SimisageBackpic:     INCBIN "gfx/pokemon/simisage/back.2bpp.lz"
GruntfPic:           INCBIN "gfx/trainers/grunt_f.2bpp.lz"
PorygonFrontpic:     INCBIN "gfx/pokemon/porygon/front.2bpp.lz"
HoOhBackpic:         INCBIN "gfx/pokemon/ho_oh/back.2bpp.lz"
ElgyemBackpic:       INCBIN "gfx/pokemon/elgyem/back.2bpp.lz"
DarmanitanBackpic:   INCBIN "gfx/pokemon/darmanitan/back.2bpp.lz"
MewBackpic:          INCBIN "gfx/pokemon/mew/back.2bpp.lz"
DwebbleBackpic:      INCBIN "gfx/pokemon/dwebble/back.2bpp.lz"
ScraftyBackpic:      INCBIN "gfx/pokemon/scrafty/back.2bpp.lz"
ScolipedeBackpic:    INCBIN "gfx/pokemon/scolipede/back.2bpp.lz"
AerodactylBackpic:   INCBIN "gfx/pokemon/aerodactyl/back.2bpp.lz"
ZebstrikaBackpic:    INCBIN "gfx/pokemon/zebstrika/back.2bpp.lz"
TirtougaBackpic:     INCBIN "gfx/pokemon/tirtouga/back.2bpp.lz"
MienshaoBackpic:     INCBIN "gfx/pokemon/mienshao/back.2bpp.lz"
GarbodorBackpic:     INCBIN "gfx/pokemon/garbodor/back.2bpp.lz"
EspeonBackpic:       INCBIN "gfx/pokemon/espeon/back.2bpp.lz"
CyndaquilFrontpic:   INCBIN "gfx/pokemon/cyndaquil/front.2bpp.lz"
TotodileBackpic:     INCBIN "gfx/pokemon/totodile/back.2bpp.lz"
MurkrowFrontpic:     INCBIN "gfx/pokemon/murkrow/front.2bpp.lz"
BasculinFrontpic:    INCBIN "gfx/pokemon/basculin/front.2bpp.lz"
SnubbullBackpic:     INCBIN "gfx/pokemon/snubbull/back.2bpp.lz"
JellicentBackpic:    INCBIN "gfx/pokemon/jellicent/back.2bpp.lz"
KarrablastBackpic:   INCBIN "gfx/pokemon/karrablast/back.2bpp.lz"
RattataBackpic:      INCBIN "gfx/pokemon/rattata/back.2bpp.lz"
FerrothornFrontpic:  INCBIN "gfx/pokemon/ferrothorn/front.2bpp.lz"
DwebbleFrontpic:     INCBIN "gfx/pokemon/dwebble/front.2bpp.lz"
YoungsterPic:        INCBIN "gfx/trainers/youngster.2bpp.lz"
WillPic:             INCBIN "gfx/trainers/will.2bpp.lz"
SchoolboyPic:        INCBIN "gfx/trainers/schoolboy.2bpp.lz"
ErikaPic:            INCBIN "gfx/trainers/erika.2bpp.lz"
DrilburBackpic:      INCBIN "gfx/pokemon/drilbur/back.2bpp.lz"
UmbreonFrontpic:     INCBIN "gfx/pokemon/umbreon/front.2bpp.lz"
JaninePic:           INCBIN "gfx/trainers/janine.2bpp.lz"
BearticFrontpic:     INCBIN "gfx/pokemon/beartic/front.2bpp.lz"
HaxorusFrontpic:     INCBIN "gfx/pokemon/haxorus/front.2bpp.lz"
ExcadrillBackpic:    INCBIN "gfx/pokemon/excadrill/back.2bpp.lz"
MortyPic:            INCBIN "gfx/trainers/morty.2bpp.lz"
KabutoBackpic:       INCBIN "gfx/pokemon/kabuto/back.2bpp.lz"
MeganiumBackpic:     INCBIN "gfx/pokemon/meganium/back.2bpp.lz"
CottoneeBackpic:     INCBIN "gfx/pokemon/cottonee/back.2bpp.lz"
UnownZBackpic:       INCBIN "gfx/pokemon/unown_z/back.2bpp.lz"


SECTION "Pics 9", ROMX

SuperNerdPic:        INCBIN "gfx/trainers/super_nerd.2bpp.lz"
TynamoBackpic:       INCBIN "gfx/pokemon/tynamo/back.2bpp.lz"
Porygon2Backpic:     INCBIN "gfx/pokemon/porygon2/back.2bpp.lz"
EmolgaBackpic:       INCBIN "gfx/pokemon/emolga/back.2bpp.lz"
SolosisBackpic:      INCBIN "gfx/pokemon/solosis/back.2bpp.lz"
JasminePic:          INCBIN "gfx/trainers/jasmine.2bpp.lz"
PinecoBackpic:       INCBIN "gfx/pokemon/pineco/back.2bpp.lz"
SlugmaBackpic:       INCBIN "gfx/pokemon/slugma/back.2bpp.lz"
DucklettBackpic:     INCBIN "gfx/pokemon/ducklett/back.2bpp.lz"
QuagsireBackpic:     INCBIN "gfx/pokemon/quagsire/back.2bpp.lz"
WhitneyPic:          INCBIN "gfx/trainers/whitney.2bpp.lz"
VanilluxeFrontpic:   INCBIN "gfx/pokemon/vanilluxe/front.2bpp.lz"
JolteonBackpic:      INCBIN "gfx/pokemon/jolteon/back.2bpp.lz"
MunnaFrontpic:       INCBIN "gfx/pokemon/munna/front.2bpp.lz"
SwadloonBackpic:     INCBIN "gfx/pokemon/swadloon/back.2bpp.lz"
MagbyFrontpic:       INCBIN "gfx/pokemon/magby/front.2bpp.lz"
QuagsireFrontpic:    INCBIN "gfx/pokemon/quagsire/front.2bpp.lz"
GranbullBackpic:     INCBIN "gfx/pokemon/granbull/back.2bpp.lz"
LampentBackpic:      INCBIN "gfx/pokemon/lampent/back.2bpp.lz"
BluePic:             INCBIN "gfx/trainers/blue.2bpp.lz"
GentlemanPic:        INCBIN "gfx/trainers/gentleman.2bpp.lz"
ExecutivemPic:       INCBIN "gfx/trainers/executive_m.2bpp.lz"
PinecoFrontpic:      INCBIN "gfx/pokemon/pineco/front.2bpp.lz"
MagbyBackpic:        INCBIN "gfx/pokemon/magby/back.2bpp.lz"
LaprasBackpic:       INCBIN "gfx/pokemon/lapras/back.2bpp.lz"
ChikoritaBackpic:    INCBIN "gfx/pokemon/chikorita/back.2bpp.lz"
DragonairBackpic:    INCBIN "gfx/pokemon/dragonair/back.2bpp.lz"
ZapdosBackpic:       INCBIN "gfx/pokemon/zapdos/back.2bpp.lz"
TepigFrontpic:       INCBIN "gfx/pokemon/tepig/front.2bpp.lz"
AudinoBackpic:       INCBIN "gfx/pokemon/audino/back.2bpp.lz"
DrilburFrontpic:     INCBIN "gfx/pokemon/drilbur/front.2bpp.lz"
PanpourBackpic:      INCBIN "gfx/pokemon/panpour/back.2bpp.lz"
ChanseyBackpic:      INCBIN "gfx/pokemon/chansey/back.2bpp.lz"
ScraftyFrontpic:     INCBIN "gfx/pokemon/scrafty/front.2bpp.lz"
StunfiskBackpic:     INCBIN "gfx/pokemon/stunfisk/back.2bpp.lz"
TotodileFrontpic:    INCBIN "gfx/pokemon/totodile/front.2bpp.lz"
Rival2Pic:           INCBIN "gfx/trainers/rival2.2bpp.lz"
TepigBackpic:        INCBIN "gfx/pokemon/tepig/back.2bpp.lz"
MistyPic:            INCBIN "gfx/trainers/misty.2bpp.lz"
CofagrigusFrontpic:  INCBIN "gfx/pokemon/cofagrigus/front.2bpp.lz"
UnfezantFrontpic:    INCBIN "gfx/pokemon/unfezant/front.2bpp.lz"
BlainePic:           INCBIN "gfx/trainers/blaine.2bpp.lz"
SlugmaFrontpic:      INCBIN "gfx/pokemon/slugma/front.2bpp.lz"
TyrogueFrontpic:     INCBIN "gfx/pokemon/tyrogue/front.2bpp.lz"
LarvitarBackpic:     INCBIN "gfx/pokemon/larvitar/back.2bpp.lz"
SunkernBackpic:      INCBIN "gfx/pokemon/sunkern/back.2bpp.lz"
PorygonBackpic:      INCBIN "gfx/pokemon/porygon/back.2bpp.lz"
ClefairyFrontpic:    INCBIN "gfx/pokemon/clefairy/front.2bpp.lz"
SnivyBackpic:        INCBIN "gfx/pokemon/snivy/back.2bpp.lz"


SECTION "Pics 10", ROMX

SewaddleBackpic:     INCBIN "gfx/pokemon/sewaddle/back.2bpp.lz"
HoundourFrontpic:    INCBIN "gfx/pokemon/houndour/front.2bpp.lz"
MareepFrontpic:      INCBIN "gfx/pokemon/mareep/front.2bpp.lz"
ArchenBackpic:       INCBIN "gfx/pokemon/archen/back.2bpp.lz"
DuosionFrontpic:     INCBIN "gfx/pokemon/duosion/front.2bpp.lz"
OmanyteFrontpic:     INCBIN "gfx/pokemon/omanyte/front.2bpp.lz"
EeveeFrontpic:       INCBIN "gfx/pokemon/eevee/front.2bpp.lz"
VaporeonBackpic:     INCBIN "gfx/pokemon/vaporeon/back.2bpp.lz"
ExecutivefPic:       INCBIN "gfx/trainers/executive_f.2bpp.lz"
LilligantBackpic:    INCBIN "gfx/pokemon/lilligant/back.2bpp.lz"
CorsolaBackpic:      INCBIN "gfx/pokemon/corsola/back.2bpp.lz"
GurdurrFrontpic:     INCBIN "gfx/pokemon/gurdurr/front.2bpp.lz"
KrookodileBackpic:   INCBIN "gfx/pokemon/krookodile/back.2bpp.lz"
SmoochumBackpic:     INCBIN "gfx/pokemon/smoochum/back.2bpp.lz"
DunsparceBackpic:    INCBIN "gfx/pokemon/dunsparce/back.2bpp.lz"
CofagrigusBackpic:   INCBIN "gfx/pokemon/cofagrigus/back.2bpp.lz"
VanillishFrontpic:   INCBIN "gfx/pokemon/vanillish/front.2bpp.lz"
SmoochumFrontpic:    INCBIN "gfx/pokemon/smoochum/front.2bpp.lz"
ChikoritaFrontpic:   INCBIN "gfx/pokemon/chikorita/front.2bpp.lz"
PidoveFrontpic:      INCBIN "gfx/pokemon/pidove/front.2bpp.lz"
PansageBackpic:      INCBIN "gfx/pokemon/pansage/back.2bpp.lz"
BearticBackpic:      INCBIN "gfx/pokemon/beartic/back.2bpp.lz"
ShelmetBackpic:      INCBIN "gfx/pokemon/shelmet/back.2bpp.lz"
PatratBackpic:       INCBIN "gfx/pokemon/patrat/back.2bpp.lz"
PrycePic:            INCBIN "gfx/trainers/pryce.2bpp.lz"
TimburrBackpic:      INCBIN "gfx/pokemon/timburr/back.2bpp.lz"
BrockPic:            INCBIN "gfx/trainers/brock.2bpp.lz"
AmpharosBackpic:     INCBIN "gfx/pokemon/ampharos/back.2bpp.lz"
RemoraidFrontpic:    INCBIN "gfx/pokemon/remoraid/front.2bpp.lz"
DragoniteBackpic:    INCBIN "gfx/pokemon/dragonite/back.2bpp.lz"
LiepardFrontpic:     INCBIN "gfx/pokemon/liepard/front.2bpp.lz"
TympoleFrontpic:     INCBIN "gfx/pokemon/tympole/front.2bpp.lz"
MusharnaBackpic:     INCBIN "gfx/pokemon/musharna/back.2bpp.lz"
EnteiBackpic:        INCBIN "gfx/pokemon/entei/back.2bpp.lz"
KlangBackpic:        INCBIN "gfx/pokemon/klang/back.2bpp.lz"
SewaddleFrontpic:    INCBIN "gfx/pokemon/sewaddle/front.2bpp.lz"
UrsaringBackpic:     INCBIN "gfx/pokemon/ursaring/back.2bpp.lz"
TeddiursaBackpic:    INCBIN "gfx/pokemon/teddiursa/back.2bpp.lz"
SagePic:             INCBIN "gfx/trainers/sage.2bpp.lz"
StoutlandBackpic:    INCBIN "gfx/pokemon/stoutland/back.2bpp.lz"
PhanpyBackpic:       INCBIN "gfx/pokemon/phanpy/back.2bpp.lz"
StunfiskFrontpic:    INCBIN "gfx/pokemon/stunfisk/front.2bpp.lz"
CelebiFrontpic:      INCBIN "gfx/pokemon/celebi/front.2bpp.lz"
DratiniFrontpic:     INCBIN "gfx/pokemon/dratini/front.2bpp.lz"
WobbuffetBackpic:    INCBIN "gfx/pokemon/wobbuffet/back.2bpp.lz"
ArchenFrontpic:      INCBIN "gfx/pokemon/archen/front.2bpp.lz"
PetililBackpic:      INCBIN "gfx/pokemon/petilil/back.2bpp.lz"
BlisseyBackpic:      INCBIN "gfx/pokemon/blissey/back.2bpp.lz"
LarvitarFrontpic:    INCBIN "gfx/pokemon/larvitar/front.2bpp.lz"
CryogonalBackpic:    INCBIN "gfx/pokemon/cryogonal/back.2bpp.lz"
KrokorokBackpic:     INCBIN "gfx/pokemon/krokorok/back.2bpp.lz"
JoltikFrontpic:      INCBIN "gfx/pokemon/joltik/front.2bpp.lz"
EelektrikBackpic:    INCBIN "gfx/pokemon/eelektrik/back.2bpp.lz"
PanpourFrontpic:     INCBIN "gfx/pokemon/panpour/front.2bpp.lz"


SECTION "Pics 11", ROMX

ArticunoBackpic:     INCBIN "gfx/pokemon/articuno/back.2bpp.lz"
LampentFrontpic:     INCBIN "gfx/pokemon/lampent/front.2bpp.lz"
MewFrontpic:         INCBIN "gfx/pokemon/mew/front.2bpp.lz"
AxewBackpic:         INCBIN "gfx/pokemon/axew/back.2bpp.lz"
PansearBackpic:      INCBIN "gfx/pokemon/pansear/back.2bpp.lz"
ConkeldurrBackpic:   INCBIN "gfx/pokemon/conkeldurr/back.2bpp.lz"
QwilfishFrontpic:    INCBIN "gfx/pokemon/qwilfish/front.2bpp.lz"
TeddiursaFrontpic:   INCBIN "gfx/pokemon/teddiursa/front.2bpp.lz"
DittoBackpic:        INCBIN "gfx/pokemon/ditto/back.2bpp.lz"
HerdierBackpic:      INCBIN "gfx/pokemon/herdier/back.2bpp.lz"
ShuckleFrontpic:     INCBIN "gfx/pokemon/shuckle/front.2bpp.lz"
PhanpyFrontpic:      INCBIN "gfx/pokemon/phanpy/front.2bpp.lz"
PansearFrontpic:     INCBIN "gfx/pokemon/pansear/front.2bpp.lz"
DarumakaFrontpic:    INCBIN "gfx/pokemon/darumaka/front.2bpp.lz"
CleffaBackpic:       INCBIN "gfx/pokemon/cleffa/back.2bpp.lz"
FoongusBackpic:      INCBIN "gfx/pokemon/foongus/back.2bpp.lz"
SawsbuckBackpic:     INCBIN "gfx/pokemon/sawsbuck/back.2bpp.lz"
DratiniBackpic:      INCBIN "gfx/pokemon/dratini/back.2bpp.lz"
SimipourBackpic:     INCBIN "gfx/pokemon/simipour/back.2bpp.lz"
VanillishBackpic:    INCBIN "gfx/pokemon/vanillish/back.2bpp.lz"
WooperFrontpic:      INCBIN "gfx/pokemon/wooper/front.2bpp.lz"
HoundourBackpic:     INCBIN "gfx/pokemon/houndour/back.2bpp.lz"
KabutoFrontpic:      INCBIN "gfx/pokemon/kabuto/front.2bpp.lz"
JoltikBackpic:       INCBIN "gfx/pokemon/joltik/back.2bpp.lz"
WatchogBackpic:      INCBIN "gfx/pokemon/watchog/back.2bpp.lz"
GurdurrBackpic:      INCBIN "gfx/pokemon/gurdurr/back.2bpp.lz"
SeismitoadBackpic:   INCBIN "gfx/pokemon/seismitoad/back.2bpp.lz"
SunkernFrontpic:     INCBIN "gfx/pokemon/sunkern/front.2bpp.lz"
SpinarakBackpic:     INCBIN "gfx/pokemon/spinarak/back.2bpp.lz"
SkarmoryBackpic:     INCBIN "gfx/pokemon/skarmory/back.2bpp.lz"
DarumakaBackpic:     INCBIN "gfx/pokemon/darumaka/back.2bpp.lz"
OshawottBackpic:     INCBIN "gfx/pokemon/oshawott/back.2bpp.lz"
SwannaBackpic:       INCBIN "gfx/pokemon/swanna/back.2bpp.lz"
ShuckleBackpic:      INCBIN "gfx/pokemon/shuckle/back.2bpp.lz"
CinccinoBackpic:     INCBIN "gfx/pokemon/cinccino/back.2bpp.lz"
TrubbishFrontpic:    INCBIN "gfx/pokemon/trubbish/front.2bpp.lz"
DonphanBackpic:      INCBIN "gfx/pokemon/donphan/back.2bpp.lz"
WooperBackpic:       INCBIN "gfx/pokemon/wooper/back.2bpp.lz"
GolettBackpic:       INCBIN "gfx/pokemon/golett/back.2bpp.lz"
HerdierFrontpic:     INCBIN "gfx/pokemon/herdier/front.2bpp.lz"
CleffaFrontpic:      INCBIN "gfx/pokemon/cleffa/front.2bpp.lz"
AlomomolaBackpic:    INCBIN "gfx/pokemon/alomomola/back.2bpp.lz"
SnivyFrontpic:       INCBIN "gfx/pokemon/snivy/front.2bpp.lz"
SwinubBackpic:       INCBIN "gfx/pokemon/swinub/back.2bpp.lz"
TangelaBackpic:      INCBIN "gfx/pokemon/tangela/back.2bpp.lz"
SpinarakFrontpic:    INCBIN "gfx/pokemon/spinarak/front.2bpp.lz"
ZoruaBackpic:        INCBIN "gfx/pokemon/zorua/back.2bpp.lz"
MantineBackpic:      INCBIN "gfx/pokemon/mantine/back.2bpp.lz"
AxewFrontpic:        INCBIN "gfx/pokemon/axew/front.2bpp.lz"
PiloswineBackpic:    INCBIN "gfx/pokemon/piloswine/back.2bpp.lz"
StoutlandFrontpic:   INCBIN "gfx/pokemon/stoutland/front.2bpp.lz"
SwinubFrontpic:      INCBIN "gfx/pokemon/swinub/front.2bpp.lz"
GothitelleBackpic:   INCBIN "gfx/pokemon/gothitelle/back.2bpp.lz"
WhirlipedeFrontpic:  INCBIN "gfx/pokemon/whirlipede/front.2bpp.lz"
WhirlipedeBackpic:   INCBIN "gfx/pokemon/whirlipede/back.2bpp.lz"
UnownCFrontpic:      INCBIN "gfx/pokemon/unown_c/front.2bpp.lz"
KrookodileFrontpic:  INCBIN "gfx/pokemon/krookodile/front.2bpp.lz"
JynxBackpic:         INCBIN "gfx/pokemon/jynx/back.2bpp.lz"
UnownHBackpic:       INCBIN "gfx/pokemon/unown_h/back.2bpp.lz"
PalpitoadBackpic:    INCBIN "gfx/pokemon/palpitoad/back.2bpp.lz"
UnownGFrontpic:      INCBIN "gfx/pokemon/unown_g/front.2bpp.lz"
UnownVBackpic:       INCBIN "gfx/pokemon/unown_v/back.2bpp.lz"
UnownCBackpic:       INCBIN "gfx/pokemon/unown_c/back.2bpp.lz"


SECTION "Pics 12", ROMX

SuicuneFrontpic:     INCBIN "gfx/pokemon/suicune/front.2bpp.lz"
ElgyemFrontpic:      INCBIN "gfx/pokemon/elgyem/front.2bpp.lz"
TyranitarFrontpic:   INCBIN "gfx/pokemon/tyranitar/front.2bpp.lz"
MoltresFrontpic:     INCBIN "gfx/pokemon/moltres/front.2bpp.lz"
ZapdosFrontpic:      INCBIN "gfx/pokemon/zapdos/front.2bpp.lz"
CubchooFrontpic:     INCBIN "gfx/pokemon/cubchoo/front.2bpp.lz"
MukFrontpic:         INCBIN "gfx/pokemon/muk/front.2bpp.lz"
DragoniteFrontpic:   INCBIN "gfx/pokemon/dragonite/front.2bpp.lz"
ScraggyFrontpic:     INCBIN "gfx/pokemon/scraggy/front.2bpp.lz"
AerodactylFrontpic:  INCBIN "gfx/pokemon/aerodactyl/front.2bpp.lz"
TyphlosionFrontpic:  INCBIN "gfx/pokemon/typhlosion/front.2bpp.lz"
SigilyphFrontpic:    INCBIN "gfx/pokemon/sigilyph/front.2bpp.lz"
GalvantulaFrontpic:  INCBIN "gfx/pokemon/galvantula/front.2bpp.lz"
FirebreatherPic:     INCBIN "gfx/trainers/firebreather.2bpp.lz"
ScizorFrontpic:      INCBIN "gfx/pokemon/scizor/front.2bpp.lz"
ArticunoFrontpic:    INCBIN "gfx/pokemon/articuno/front.2bpp.lz"
ReuniclusFrontpic:   INCBIN "gfx/pokemon/reuniclus/front.2bpp.lz"
LillipupFrontpic:    INCBIN "gfx/pokemon/lillipup/front.2bpp.lz"
SimisageFrontpic:    INCBIN "gfx/pokemon/simisage/front.2bpp.lz"
WhimsicottFrontpic:  INCBIN "gfx/pokemon/whimsicott/front.2bpp.lz"
SwannaFrontpic:      INCBIN "gfx/pokemon/swanna/front.2bpp.lz"
DeerlingFrontpic:    INCBIN "gfx/pokemon/deerling/front.2bpp.lz"
EscavalierFrontpic:  INCBIN "gfx/pokemon/escavalier/front.2bpp.lz"
ChampionPic:         INCBIN "gfx/trainers/champion.2bpp.lz"
SlowkingFrontpic:    INCBIN "gfx/pokemon/slowking/front.2bpp.lz"
CarracostaFrontpic:  INCBIN "gfx/pokemon/carracosta/front.2bpp.lz"
BlackbeltTPic:       INCBIN "gfx/trainers/blackbelt_t.2bpp.lz"
RattataFrontpic:     INCBIN "gfx/pokemon/rattata/front.2bpp.lz"
CinccinoFrontpic:    INCBIN "gfx/pokemon/cinccino/front.2bpp.lz"
JellicentFrontpic_F: INCBIN "gfx/pokemon/jellicent_f/front.2bpp.lz"
JellicentBackpic_F:  INCBIN "gfx/pokemon/jellicent_f/back.2bpp.lz"
OshawottFrontpic:    INCBIN "gfx/pokemon/oshawott/front.2bpp.lz"


SECTION "Pics 13", ROMX

AmoongussFrontpic:   INCBIN "gfx/pokemon/amoonguss/front.2bpp.lz"
BlisseyFrontpic:     INCBIN "gfx/pokemon/blissey/front.2bpp.lz"
BikerPic:            INCBIN "gfx/trainers/biker.2bpp.lz"
SandileFrontpic:     INCBIN "gfx/pokemon/sandile/front.2bpp.lz"
TranquillFrontpic:   INCBIN "gfx/pokemon/tranquill/front.2bpp.lz"
StantlerFrontpic:    INCBIN "gfx/pokemon/stantler/front.2bpp.lz"
FerroseedFrontpic:   INCBIN "gfx/pokemon/ferroseed/front.2bpp.lz"
BrunoPic:            INCBIN "gfx/trainers/bruno.2bpp.lz"
ForretressFrontpic:  INCBIN "gfx/pokemon/forretress/front.2bpp.lz"
MagmarFrontpic:      INCBIN "gfx/pokemon/magmar/front.2bpp.lz"
HikerPic:            INCBIN "gfx/trainers/hiker.2bpp.lz"
EelektrikFrontpic:   INCBIN "gfx/pokemon/eelektrik/front.2bpp.lz"
JellicentFrontpic:   INCBIN "gfx/pokemon/jellicent/front.2bpp.lz"
MaractusFrontpic:    INCBIN "gfx/pokemon/maractus/front.2bpp.lz"
DruddigonFrontpic:   INCBIN "gfx/pokemon/druddigon/front.2bpp.lz"
MewtwoFrontpic:      INCBIN "gfx/pokemon/mewtwo/front.2bpp.lz"
GothitaFrontpic:     INCBIN "gfx/pokemon/gothita/front.2bpp.lz"
CrustleFrontpic:     INCBIN "gfx/pokemon/crustle/front.2bpp.lz"
SnorlaxFrontpic:     INCBIN "gfx/pokemon/snorlax/front.2bpp.lz"
MediumPic:           INCBIN "gfx/trainers/medium.2bpp.lz"
DonphanFrontpic:     INCBIN "gfx/pokemon/donphan/front.2bpp.lz"
MantineFrontpic:     INCBIN "gfx/pokemon/mantine/front.2bpp.lz"
HitmontopFrontpic:   INCBIN "gfx/pokemon/hitmontop/front.2bpp.lz"
FisherPic:           INCBIN "gfx/trainers/fisher.2bpp.lz"
LitwickFrontpic:     INCBIN "gfx/pokemon/litwick/front.2bpp.lz"
ElectabuzzFrontpic:  INCBIN "gfx/pokemon/electabuzz/front.2bpp.lz"
ArcheopsFrontpic:    INCBIN "gfx/pokemon/archeops/front.2bpp.lz"
SwoobatBackpic:      INCBIN "gfx/pokemon/swoobat/back.2bpp.lz"
PokefanmPic:         INCBIN "gfx/trainers/pokefan_m.2bpp.lz"
BoarderPic:          INCBIN "gfx/trainers/boarder.2bpp.lz"
UrsaringFrontpic:    INCBIN "gfx/pokemon/ursaring/front.2bpp.lz"
YamaskBackpic:       INCBIN "gfx/pokemon/yamask/back.2bpp.lz"
LeavannyFrontpic:    INCBIN "gfx/pokemon/leavanny/front.2bpp.lz"


SECTION "Pics 14", ROMX

UnownHFrontpic:      INCBIN "gfx/pokemon/unown_h/front.2bpp.lz"
DittoFrontpic:       INCBIN "gfx/pokemon/ditto/front.2bpp.lz"
SnorlaxBackpic:      INCBIN "gfx/pokemon/snorlax/back.2bpp.lz"
MagnemiteBackpic:    INCBIN "gfx/pokemon/magnemite/back.2bpp.lz"
UnownGBackpic:       INCBIN "gfx/pokemon/unown_g/back.2bpp.lz"
ForretressBackpic:   INCBIN "gfx/pokemon/forretress/back.2bpp.lz"
GothitelleFrontpic:  INCBIN "gfx/pokemon/gothitelle/front.2bpp.lz"
UnownSFrontpic:      INCBIN "gfx/pokemon/unown_s/front.2bpp.lz"
UnownVFrontpic:      INCBIN "gfx/pokemon/unown_v/front.2bpp.lz"
UnownFBackpic:       INCBIN "gfx/pokemon/unown_f/back.2bpp.lz"
UnownDBackpic:       INCBIN "gfx/pokemon/unown_d/back.2bpp.lz"
UnownDFrontpic:      INCBIN "gfx/pokemon/unown_d/front.2bpp.lz"
UnownSBackpic:       INCBIN "gfx/pokemon/unown_s/back.2bpp.lz"
UnownEFrontpic:      INCBIN "gfx/pokemon/unown_e/front.2bpp.lz"
UnownEBackpic:       INCBIN "gfx/pokemon/unown_e/back.2bpp.lz"
AlomomolaFrontpic:   INCBIN "gfx/pokemon/alomomola/front.2bpp.lz"
MagnemiteFrontpic:   INCBIN "gfx/pokemon/magnemite/front.2bpp.lz"
UnownZFrontpic:      INCBIN "gfx/pokemon/unown_z/front.2bpp.lz"
UnownBFrontpic:      INCBIN "gfx/pokemon/unown_b/front.2bpp.lz"
UnownFFrontpic:      INCBIN "gfx/pokemon/unown_f/front.2bpp.lz"
UnownJBackpic:       INCBIN "gfx/pokemon/unown_j/back.2bpp.lz"
UnownBBackpic:       INCBIN "gfx/pokemon/unown_b/back.2bpp.lz"
UnownWFrontpic:      INCBIN "gfx/pokemon/unown_w/front.2bpp.lz"
UnownOBackpic:       INCBIN "gfx/pokemon/unown_o/back.2bpp.lz"
UnownJFrontpic:      INCBIN "gfx/pokemon/unown_j/front.2bpp.lz"
UnownWBackpic:       INCBIN "gfx/pokemon/unown_w/back.2bpp.lz"
UnownNFrontpic:      INCBIN "gfx/pokemon/unown_n/front.2bpp.lz"
UnownKFrontpic:      INCBIN "gfx/pokemon/unown_k/front.2bpp.lz"
UnownNBackpic:       INCBIN "gfx/pokemon/unown_n/back.2bpp.lz"
UnownABackpic:       INCBIN "gfx/pokemon/unown_a/back.2bpp.lz"
UnownAFrontpic:      INCBIN "gfx/pokemon/unown_a/front.2bpp.lz"
UnownMBackpic:       INCBIN "gfx/pokemon/unown_m/back.2bpp.lz"
UnownTFrontpic:      INCBIN "gfx/pokemon/unown_t/front.2bpp.lz"
UnownOFrontpic:      INCBIN "gfx/pokemon/unown_o/front.2bpp.lz"
UnownKBackpic:       INCBIN "gfx/pokemon/unown_k/back.2bpp.lz"
UnownTBackpic:       INCBIN "gfx/pokemon/unown_t/back.2bpp.lz"
UnownXBackpic:       INCBIN "gfx/pokemon/unown_x/back.2bpp.lz"
UnownMFrontpic:      INCBIN "gfx/pokemon/unown_m/front.2bpp.lz"
UnownLBackpic:       INCBIN "gfx/pokemon/unown_l/back.2bpp.lz"
UnownUBackpic:       INCBIN "gfx/pokemon/unown_u/back.2bpp.lz"
UnownLFrontpic:      INCBIN "gfx/pokemon/unown_l/front.2bpp.lz"
UnownYFrontpic:      INCBIN "gfx/pokemon/unown_y/front.2bpp.lz"
UnownXFrontpic:      INCBIN "gfx/pokemon/unown_x/front.2bpp.lz"
UnownQBackpic:       INCBIN "gfx/pokemon/unown_q/back.2bpp.lz"
UnownQFrontpic:      INCBIN "gfx/pokemon/unown_q/front.2bpp.lz"
UnownPFrontpic:      INCBIN "gfx/pokemon/unown_p/front.2bpp.lz"
UnownYBackpic:       INCBIN "gfx/pokemon/unown_y/back.2bpp.lz"
UnownIBackpic:       INCBIN "gfx/pokemon/unown_i/back.2bpp.lz"
UnownPBackpic:       INCBIN "gfx/pokemon/unown_p/back.2bpp.lz"
UnownIFrontpic:      INCBIN "gfx/pokemon/unown_i/front.2bpp.lz"
UnownRBackpic:       INCBIN "gfx/pokemon/unown_r/back.2bpp.lz"
UnownRFrontpic:      INCBIN "gfx/pokemon/unown_r/front.2bpp.lz"

SECTION "Pics 15", ROMX
KingdraFrontpic:     INCBIN "gfx/pokemon/kingdra/front.2bpp.lz"
BlitzleFrontpic:     INCBIN "gfx/pokemon/blitzle/front.2bpp.lz"
GarbodorFrontpic:    INCBIN "gfx/pokemon/garbodor/front.2bpp.lz"
ShelmetFrontpic:     INCBIN "gfx/pokemon/shelmet/front.2bpp.lz"
SerperiorBackpic:    INCBIN "gfx/pokemon/serperior/back.2bpp.lz"
MoltresBackpic:      INCBIN "gfx/pokemon/moltres/back.2bpp.lz"
StantlerBackpic:     INCBIN "gfx/pokemon/stantler/back.2bpp.lz"
EmboarBackpic:       INCBIN "gfx/pokemon/emboar/back.2bpp.lz"
PsyduckFrontpic:     INCBIN "gfx/pokemon/psyduck/front.2bpp.lz"
GrowlitheFrontpic:   INCBIN "gfx/pokemon/growlithe/front.2bpp.lz"
PicnickerPic:        INCBIN "gfx/trainers/picnicker.2bpp.lz"
CarracostaBackpic:   INCBIN "gfx/pokemon/carracosta/back.2bpp.lz"
Porygon2Frontpic:    INCBIN "gfx/pokemon/porygon2/front.2bpp.lz"
LitwickBackpic:      INCBIN "gfx/pokemon/litwick/back.2bpp.lz"
OctilleryBackpic:    INCBIN "gfx/pokemon/octillery/back.2bpp.lz"
RaikouBackpic:       INCBIN "gfx/pokemon/raikou/back.2bpp.lz"
RattataFrontpic_F:   INCBIN "gfx/pokemon/rattata_f/front.2bpp.lz"
RattataBackpic_F:    INCBIN "gfx/pokemon/rattata_f/back.2bpp.lz"
RaticateFrontpic_F:  INCBIN "gfx/pokemon/raticate_f/front.2bpp.lz"
RaticateBackpic_F:   INCBIN "gfx/pokemon/raticate_f/back.2bpp.lz"
MagikarpFrontpic_F:  INCBIN "gfx/pokemon/magikarp_f/front.2bpp.lz"
MagikarpBackpic_F:   INCBIN "gfx/pokemon/magikarp_f/back.2bpp.lz"
GyaradosFrontpic_F:  INCBIN "gfx/pokemon/gyarados_f/front.2bpp.lz"
GyaradosBackpic_F:   INCBIN "gfx/pokemon/gyarados_f/back.2bpp.lz"
LedybaFrontpic_F:    INCBIN "gfx/pokemon/ledyba_f/front.2bpp.lz"
LedybaBackpic_F:     INCBIN "gfx/pokemon/ledyba_f/back.2bpp.lz"
LedianFrontpic_F:    INCBIN "gfx/pokemon/ledian_f/front.2bpp.lz"
LedianBackpic_F:     INCBIN "gfx/pokemon/ledian_f/back.2bpp.lz"
SneaselFrontpic_F:   INCBIN "gfx/pokemon/sneasel_f/front.2bpp.lz"
SneaselBackpic_F:    INCBIN "gfx/pokemon/sneasel_f/back.2bpp.lz"
GligarFrontpic_F:    INCBIN "gfx/pokemon/gligar_f/front.2bpp.lz"
GligarBackpic_F:     INCBIN "gfx/pokemon/gligar_f/back.2bpp.lz"
HoundoomFrontpic_F:  INCBIN "gfx/pokemon/houndoom_f/front.2bpp.lz"
HoundoomBackpic_F:   INCBIN "gfx/pokemon/houndoom_f/back.2bpp.lz"
MurkrowFrontpic_F:   INCBIN "gfx/pokemon/murkrow_f/front.2bpp.lz"
MurkrowBackpic_F:    INCBIN "gfx/pokemon/murkrow_f/back.2bpp.lz"
PiloswineFrontpic_F: INCBIN "gfx/pokemon/piloswine_f/front.2bpp.lz"
PiloswineBackpic_F:  INCBIN "gfx/pokemon/piloswine_f/back.2bpp.lz"

SECTION "Pics 16", ROMX
RedPic:              INCBIN "gfx/trainers/red.2bpp.lz"
FlaaffyFrontpic:     INCBIN "gfx/pokemon/flaaffy/front.2bpp.lz"
VaporeonFrontpic:    INCBIN "gfx/pokemon/vaporeon/front.2bpp.lz"
JynxFrontpic:        INCBIN "gfx/pokemon/jynx/front.2bpp.lz"
MagikarpFrontpic:    INCBIN "gfx/pokemon/magikarp/front.2bpp.lz"
LedybaFrontpic:      INCBIN "gfx/pokemon/ledyba/front.2bpp.lz"
GolduckFrontpic:     INCBIN "gfx/pokemon/golduck/front.2bpp.lz"
ArcanineFrontpic:    INCBIN "gfx/pokemon/arcanine/front.2bpp.lz"
PoochyenaFrontpic:   INCBIN "gfx/pokemon/poochyena/front.2bpp.lz"
PoochyenaBackpic:    INCBIN "gfx/pokemon/poochyena/back.2bpp.lz"
MightyenaFrontpic:   INCBIN "gfx/pokemon/mightyena/front.2bpp.lz"
MightyenaBackpic:    INCBIN "gfx/pokemon/mightyena/back.2bpp.lz"
WatchogFrontpic:     INCBIN "gfx/pokemon/watchog/front.2bpp.lz"
PatratFrontpic:      INCBIN "gfx/pokemon/patrat/front.2bpp.lz"
UnfezantFrontpic_F:  INCBIN "gfx/pokemon/unfezant_f/front.2bpp.lz"
UnfezantBackpic_F:   INCBIN "gfx/pokemon/unfezant_f/back.2bpp.lz"
GigalithFrontpic:    INCBIN "gfx/pokemon/gigalith/front.2bpp.lz"
SeismitoadFrontpic:  INCBIN "gfx/pokemon/seismitoad/front.2bpp.lz"
LilligantFrontpic:   INCBIN "gfx/pokemon/lilligant/front.2bpp.lz"
BasculinFrontpic_F:  INCBIN "gfx/pokemon/basculin_f/front.2bpp.lz"
BasculinBackpic_F:   INCBIN "gfx/pokemon/basculin_f/front.2bpp.lz"
KrokorokFrontpic:    INCBIN "gfx/pokemon/krokorok/front.2bpp.lz"
FrillishFrontpic_F:  INCBIN "gfx/pokemon/frillish_f/front.2bpp.lz"
FrillishBackpic_F:   INCBIN "gfx/pokemon/frillish_f/back.2bpp.lz"
MienshaoFrontpic:    INCBIN "gfx/pokemon/mienshao/front.2bpp.lz"
